### ISSUE TITLE
[Feature] Add comment on changesets

### ISSUE THREAD

**Issue by nlehuby** [e-biz/osm-contributor#2] opened 2015-06-09 09:12 UTC
Here is a changeset created by an app created with the Brest instance : 
http://www.openstreetmap.org/changeset/31578515

There is no comment on the changeset.

Please consider adding one : http://wiki.openstreetmap.org/wiki/Good_changeset_comments#Why_should_I_use_Changeset_Comments.3F

Great job by the way ;)

**Comment by loicortola** [comment] 2015-06-09 16:28
Thanks a lot for the feedback,

the changeset feature will be part of the release late june, along with comments and picture contributions.
Will keep you informed once the issue is "solved" ;)

**Comment by loicortola** [comment] 2015-06-16 09:43
We are working on this issue, here is what we think we can do:

Our first approach is "auto-commit", meaning each POI addition or update will be sent directly when the user commits.
If internet is not available, the changes will be commited into one single changeset once the connectivity is back.
For this approach, we are planning on having auto messages "Added poi X", "Updated poi Y position" ...

I understand some users like having an advanced experience ("Updated the traffic lights positions of Paris 14th district"), so we are going to add a setting to switch to "Manual commit" mode.
When you switch to manual commit mode, all your changes will not be sent automatically.
Once you are done with them, you can decide to commit and push the changeset, and put a specific comment on it.

Does that sound good?

**Comment by nlehuby** [comment] 2015-06-17 12:43
:+1:

**Closed** 2017-12-18 10:35 UTC
Labels: enhancement
